version: '3'
services:
  oacis:
    image: oacis/oacis_jupyter:${OACIS_IMAGE_TAG:-latest}
    volumes:
      - ./Result:/home/oacis/oacis/public/Result_development
      - ${HOME}/.ssh/config:/home/oacis/.ssh/config:ro
    environment:
      - LOCAL_UID
      - LOCAL_GID
      - LOCAL_USER
    ports:
      - "127.0.0.1:${OACIS_PORT:-3000}:3000"
      - "127.0.0.1:${JUPYTER_PORT:-8888}:8888"
    tty: true
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
